export const HOME = {
  FETCH_PRODUCTS: {
    MAIN: "FETCH_PRODUCTS",
    SUCCESS: "FETCH_PRODUCTS_SUCCESS",
    FAILURE: "FETCH_PRODUCTS_FAILURE",
  },
  SEARCH_PRODUCTS: {
    MAIN: "SEARCH_PRODUCTS",
    SUCCESS: "SEARCH_PRODUCTS_SUCCESS",
    FAILURE: "SEARCH_PRODUCTS_FAILURE",
  },
};
