export const AUTH = {
  OPEN_MODAL: "OPEN_MODAL",
  SET_LOGIN: {
    MAIN: "SET_LOGIN",
    SUCCESS: "SET_LOGIN_SUCCESS",
    FAILURE: "SET_LOGIN_FAILURE",
  },
  SET_SIGN_UP: {
    MAIN: "SET_SIGN_UP",
    SUCCESS: "SET_SIGN_UP_SUCCESS",
    FAILURE: "SET_SIGN_UP_FAILURE",
  },
  LOGOUT_USER: "LOGOUT_USER",
};
