export const WISHLIST = {
  FETCH_WISHLIST: {
    MAIN: "FETCH_WISHLIST",
    SUCCESS: "FETCH_WISHLIST_SUCCESS",
    FAILURE: "FETCH_WISHLIST_FAILURE",
  },
  ADD_WISHLIST: {
    MAIN: "ADD_WISHLIST",
    SUCCESS: "ADD_WISHLIST_SUCCESS",
    FAILURE: "ADD_WISHLIST_FAILURE",
  },
  REMOVE_WISHLIST: {
    MAIN: "REMOVE_WISHLIST",
    SUCCESS: "REMOVE_WISHLIST_SUCCESS",
    FAILURE: "REMOVE_WISHLIST_FAILURE",
  },
  CLEAR_WISHLIST: {
    MAIN: "CLEAR_WISHLIST",
    SUCCESS: "CLEAR_WISHLIST_SUCCESS",
    FAILURE: "CLEAR_WISHLIST_FAILURE",
  },
  CLEAR_LOGOUT: "CLEAR_LOGOUT",
  SET_CLICKED: "SET_CLICKED",
};
